language: go

go:
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"
  - "tip"

os:
  - linux
  - osx
  - windows

sudo: false

branches:
  only:
    - master
    - develop

services:
  # github.com/giovan/chango/cache
  - memcache
  - redis-server

before_install:
  # TRAVIS_OS_NAME - linux and osx
  - echo $TRAVIS_OS_NAME
  - echo $PATH
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update && brew install memcached redis && brew services start redis && brew services start memcached
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
      redis-server --daemonize yes
      redis-cli info
    else
      # redis-server.exe
      # redis-cli.exe info
      echo $PATH
    fi
install:
  # Setting environments variables
  - export PATH=$PATH:$HOME/gopath/bin
  - export CHANGO_BRANCH="develop"
  - 'if [[ "$TRAVIS_BRANCH" == "master" ]]; then export CHANGO_BRANCH="master"; fi'
  - 'echo "Travis branch: $TRAVIS_BRANCH, Chango dependency branch: $CHANGO_BRANCH"'
  - git clone -b $CHANGO_BRANCH git://github.com/chango/modules ../modules/
  - git clone -b $CHANGO_BRANCH git://github.com/chango/cmd ../cmd/
  - git clone -b $CHANGO_BRANCH git://github.com/chango/config ../config/
  - git clone -b $CHANGO_BRANCH git://github.com/chango/cron ../cron/
  - git clone -b $CHANGO_BRANCH git://github.com/chango/examples ../examples/
  - go get -t -v github.com/giovan/chango/...

script:
  - |
    if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
      go test -v github.com/giovan/chango/...
    else
      go test -v github.com/giovan/chango/.
    fi
matrix:
  allow_failures:
    - go: tip
    - os: windows